---
'ALTERNATE_DRIVING_DIRECTION': 'False'
'AWS_REGION': 'us-east-1'
'BEST_MODEL_METRIC': 'progress'
'BODY_SHELL_TYPE': 'deepracer'
'CAMERA_MAIN_ENABLE': 'True'
'CAMERA_SUB_ENABLE': 'False'
'CAR_COLOR': 'Black'
'CAR_NAME': 'MyDeepRacerCar'
'CHANGE_START_POSITION': 'True'
'DISPLAY_NAME': 'MyDeepRacerCar'
'ENABLE_DOMAIN_RANDOMIZATION': 'False'
'JOB_TYPE': 'TRAINING'
'KINESIS_VIDEO_STREAM_NAME': ''
'METRICS_S3_BUCKET': 'base-bucket-1f3pfk38sjoqu'
'METRICS_S3_OBJECT_KEY': 'AWS-Beast-B01/aws-beast-b01s/metrics/TrainingMetrics.json'
'MIN_EVAL_TRIALS': '5'
'MODEL_METADATA_FILE_S3_KEY': 'AWS-Beast-B01/custom_files/model_metadata.json'
'NUM_WORKERS': '6'
'RACER_NAME': 'MyDeepRacerCar'
'RACE_TYPE': 'TIME_TRIAL'
'REVERSE_DIR': 'True'
'REWARD_FILE_S3_KEY': 'AWS-Beast-B01/custom_files/reward_function.py'
'ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID': 'Dummy'
'ROUND_ROBIN_ADVANCE_DIST': '0.05'
'SAGEMAKER_SHARED_S3_BUCKET': 'base-bucket-1f3pfk38sjoqu'
'SAGEMAKER_SHARED_S3_PREFIX': 'AWS-Beast-B01/aws-beast-b01s'
'SIMTRACE_S3_BUCKET': 'base-bucket-1f3pfk38sjoqu'
'SIMTRACE_S3_PREFIX': 'AWS-Beast-B01/aws-beast-b01s'
'START_POSITION_OFFSET': '0.0'
'TRAINING_JOB_ARN': 'arn:Dummy'
'WORLD_NAME': '2022_september_pro'
